version: '3.8'

services:
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: MINIO_ROOT_PASSWORD
    command: server /data

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: share-images
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'

  nestjs:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./server:/app
    working_dir: /app
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/share-images
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ROOT_USER: MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: MINIO_ROOT_PASSWORD
      MINIO_USE_SSL: "false"
      API_URL: http://localhost:3001
    depends_on:
      - postgres
      - minio

  nextjs:
    build:
      context: ./client/share-images
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client/share-images:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    depends_on:
      - nestjs